[Interface]
PrivateKey = 0MwqJS5NoJm52OPHqRYsUIdZcmIUoW4+6SxpX/V50n4=
Address = 10.104.11.233/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = Fwt2sU9t7zRQye4BP/5IsO3dZjvRVR5hO5JD+6JFAEs=
Endpoint = 51.75.145.20:443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
